stages:
  - verify
  - build-container
  - deploy

verify:
  stage: verify
  script:
    - mvn clean verify

deploy on dev:
  stage: deploy
  when: manual
  tags:
    - deploy

  script:
    - ENVIRONMENT="dev"
    - APPLICATION="interaction-design-api"
    - REMOTE_SERVICE_OWNER="gitlab-runner"
    - REMOTE_FOLDER=$(echo "/opt/services/$ENVIRONMENT")$(echo "_")$(echo "$APPLICATION")
    - COMMIT_ID=$CI_COMMIT_SHORT_SHA
    - SYSTEMCTL_UNIT=$(echo "$ENVIRONMENT")$(echo "_")$(echo "$APPLICATION")
    - mvn clean package
    - cd target/
    - rename s/\.jar$/-$COMMIT_ID.jar/ *jar
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S cp *-$COMMIT_ID.jar $REMOTE_FOLDER
    - cd $REMOTE_FOLDER

    - echo $GITLAB_RUNNER_PASSWORD | sudo -S systemctl stop $SYSTEMCTL_UNIT;
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S find . -name '*.jar' ! -name "*-$COMMIT_ID.jar" -exec rm {} \;
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S ln -s *-$COMMIT_ID.jar service.jar
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S systemctl start $SYSTEMCTL_UNIT;
    - echo starting service

build release container:
  stage: build-container
  when: manual
  only:
    - tags
  tags:
    - build
  environment:
    name: container/release
  script:
    - REMOTE_REGISTRY="registry.gitlab.com"
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
    - ARTIFACTID=`mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout`
    - IMAGENAME=$REMOTE_REGISTRY/itApi/$ARTIFACTID:$VERSION-RELEASE
    - mvn clean package
    - cp target/*.jar target/app.jar
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S docker build -t $IMAGE:$COMMIT_TAG . > build-image.out
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S docker login $REMOTE_REGISTRY --username $GITLAB_USER --password $GITLAB_PASSWORD
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S docker push $IMAGENAME > push-image-release.out
    - echo $GITLAB_RUNNER_PASSWORD | sudo -S docker logout $REMOTE_REGISTRY