jwt.secret: secretfortravel
jwt.jwtExpirationInMs: 7000000 #2h
jwt.refreshExpirationDateInMs: 5000000

server.port: 5050

spring:
  application:
    name: interaction-design-api


  datasource:
    url: jdbc:postgresql://localhost/interaction-design
    username: postgres
    password: postgres
    
    hikari:
      auto-commit: false

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

        dialect: org.hibernate.dialect.PostgreSQLDialect
  

    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update

  #postgres
  #postgres_1
  #postgresQL
