jwt.secret: secretfortravel
jwt.jwtExpirationInMs: 7000000 #2h
jwt.refreshExpirationDateInMs: 5000000

server.port: 5050

template:
  link: /jasperTemplates/Booking.jrxml
  linkMitReisende: /jasperTemplates/Booking_mitReisende.jrxml
  forStream: forOutPutStream.html
  email:
    from: dovonon@th-brandenburg.de #post@university-travel-club.org
    simple-email: simple-email.html
    new-booking: new-booking.html
    update-booking: update-booking.html
    delete-booking: delete-booking.html
    html-pdf: html-pdf.html

spring:
  application:
    name: interaction-design-api


  datasource:
    url: jdbc:postgresql://localhost/interaction-design
    username: postgres_1
    password: postgresQL

    hikari:
      auto-commit: false

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

        dialect: org.hibernate.dialect.PostgreSQLDialect


    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: dovonon@th-brandenburg.de
    password: TCjYxkvJH39zM0VQ
    protocol: smtp
    #tls: true
    properties.mail.smtp:
      auth: false
      starttls.enable: false
      ssl.trust:

  #postgres
  #postgres_1
  #postgresQL
