server:
  port: 5050
spring:
    application:
         name:  interaction-design-api
               
    datasource: 
         url: jdbc:postgresql://localhost/interaction-design
         username: postgres_1 #postgres
         password: postgresQL #postgres
    
    jpa:
       show-sql: false
       generate-ddl: true
       properties:
           hibernate:
                jdbc: 
                   lob:
                      non_contextual_creation : true
                      
                dialect: org.hibernate.dialect.PostgreSQLDialect     
                
       hibernate:
       # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update


